version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
volumes:
  data:
