# fly.toml app configuration file generated for greenroyale-be on 2024-09-13T10:05:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'greenroyale-be'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3000"
  NODE_ENV = "production" 
  DATABASE_URL= "postgres://default:a0LETFpd6wBY@ep-little-forest-a4t047xh-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"
  ACCESS_TOKEN_TTL = "15*60*60"
  REFRESH_TOKEN_TTL = "7d"
  ACCESS_TOKEN_PUBLIC_KEY = "some-secret"
  REFRESH_TOKEN_PUBLIC_KEY = "some-secret"
  ACCESS_TOKEN_PRIVATE_KEY = "some-secret"
  REFRESH_TOKEN_PRIVATE_KEY = "some-secret"
  JWT_COOKIE_EXPIRES_IN = "7d"
  SWAGGER_JSON_URL = ""
  REDIS_PORT = "6379"
  REDIS_HOST = ""
  SMTP_FROM_ADDRESS="<green-royale@gmail.com>"
  SMTP_HOST = ""
  SMTP_PORT = ""
  SMTP_SECURE = ""
  SMTP_USER = ""
  SMTP_PASSWORD = ""
  BULL_BOARD_PASSWORD = "green-royale"