const HTTP_STATUS_CODE = {
  200: "SUCCESS",
  201: "SUCCESS",
  400: "BAD REQUEST",
  401: "AUTHENTICATION FAILED",
  404: "NOT FOUND",
  422: "UNPROCESSED ENTITY",
  500: "SERVER ERROR",
} as const;

export default HTTP_STATUS_CODE;
