const HTTP_STATUS_CODE = {
  200: "SUCCESSS",
  201: "CREATED",
  400: "BAD REQUEST",
  401: "AUTHENTICATION ERROR",
  404: "NOT FOUND",
  422: "UNPROCESSABLE ENTITY",
  500: "SERVER ERROR",
} as const;

export default HTTP_STATUS_CODE;
